### ISSUE TITLE
Impossible to create a template from json file

### ISSUE THREAD

**Issue by lqueiroga** [usharesoft/hammr#112]
Launching command "hammr template create --file mytemplate.json" raised an error:
File "/usr/lib/python2.7/site-packages/hammr/commands/template/template.py", line 531, in import_stack
    appImport = self.api.Users(self.login).Imports.Import(None, None, Imported=isImport, Force=isForce, Reusebundles=rbundles, Usemajor=isUseMajor)
TypeError: Import() got multiple values for keyword argument 'Imported'

Branch master is not synchronised with uforge-python sdk latest version (bug for future sdk version no regenerated yet).

**Comment by bastienmartin** [comment]
**Tested with Hammr 3.8.4 using a credential file**
I can create a template into UForge 3.8.FP4 with a hammr 3.8.4 using a YAML file :

**credentials.yml**
```
---
user: guest
publickey: uvvKK6cOqNgAkGG3UpvkqeLWswdsQ7fSPiS8FUYgMeJZj0picIaoOkckZw4tLVwCbUlE444hHf9WXePOV6
secretkey: 8838NLksOXPamDbpTgSecuo1defIM3BhSi21aj2drkQMVkJQkLZkoAgqfWmrkXlonhtaaFK0W3K2seprkE
url: http://10.1.2.52/api
acceptAutoSigned: true
```

**create_template.yml**
```
---
stack:
  name: PSTAS-69
  version: '1.0'
  installation:
    internetSettings: basic
    diskSize: 12288
    swapSize: 512
  os:
    name: CentOS
    version: '7'
    arch: x86_64
    profile: Minimal
```

`[root@009cb398a9d0 hammr-112]# hammr template create --file create_template.yml`

**THE STDOUT**
```
INFO: Checking default credentials file...
INFO: no username provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.yml
you provided a yaml file, checking the syntax...
INFO: You provided a yaml file, checking...
Creating template from temporary [/tmp/hammr-24/archive.tar.gz] archive ...
100%|#############################################################################################################################################################################################|
OK: Template create: DONE
Template URI: users/guest/appliances/504
Template Id : 504
```

**Comment by Numerinico** [comment]
@bastienmartin thk for this. Closing it.
