### ISSUE TITLE
Install Profile Internet Settings are not exported correctly

### ISSUE THREAD

**Issue by cinlloc** [usharesoft/hammr#114]
## In a nutshell
When exporting a template with *internetSettings=static*, generated archive does not contain correct *template.json*. 
## Steps
* Create *stack_centos-7-installprofile-ip.json* file with following content:
```
{
  "stack": {
    "name": "stack_centos-7_installprofile-ip",
    "version": "7",
    "os": {
      "name": "CentOS",
      "version": "7",
      "arch": "x86_64",
      "profile": "Minimal"
    },
    "installation": {
      "internetSettings": "static"
    }
  }
```
* Launch hammr console.
* Type `template create --file stack_centos-7-installprofile-ip.json` + `Enter` => appliance is created. Note provided appliance id.
* Type `template export --id <provided id> --file stack_centos-7-installprofile-ip.tar.gz` + `Enter` => archive is created
* Open *template.json* in *stack_centos-7-installprofile-ip.tar.gz* archive. 

## Expected
JSON should contain: 
```
...
"installation" : {
      "internetSettings" : "static",
      "rootUser" : {
        "password" : "",
        "sshKeys" : [ ]
      }
...
```
## Actual
But it contains:
```
...
"installation" : {
      "internetSettings" : "dhcp",
      "rootUser" : {
        "password" : "",
        "sshKeys" : [ ]
      }
...
```
## More information
* UForge AppCenter version: 3.5.1-32
* Hammr version: 0.2.5.10
* UForge Python SDK: 3.5.1.5

**Comment by lqueiroga** [comment]
The fix is done in uforge API side and not in hammr side
