### ISSUE TITLE
default "stable" version of the hammr doc should be 3.6

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#131]
Currently, if you go to the hammr documentation from hammr.io, you are in
http://docs.usharesoft.com/projects/hammr/en/stable/

However, "stable" is the hammr for UForge AppCenter 3.5.1 version.
Whereas the documentation for UForge AppCenter http://docs.usharesoft.com is the UForge AppCenter 3.6 documentation.

So, in docs.usharesoft.com/projects/hammr, "stable" should be for hammr / 3.6, not hammr / 3.5.1

**Comment by segalaj** [comment]
Hello,
This has been fixed, stable version is hammr-3.6.
Thanks
