### ISSUE TITLE
hammr hangs silently when processing a template with 1000's of rpms as MySoftware.

### ISSUE THREAD

**Issue by ntlartey** [usharesoft/hammr#14]
I create a template to contain the 1000's of rpms needed to run cPanel for centos 6.

<pre>
$ hammr template create -f --file template.json
Validating the template file [template.json] ...
OK: Syntax of template file [template.json] is ok
Downloadling file cpanel-perl-514-LWP-Protocol-https-6.03-1.cp1136.x86_64.rpm:
Status: 100% |>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>| Time: 0:00:00
Creating template from temporary [/tmp/hammr-13794/archive.tar.gz] archive ...
 10%|############ | 
</pre>

The process never progresses past the 10% status.

**Comment by jbremond** [comment]
This bug is located in the uforge product

**Comment by jbremond** [comment]
Hello,

This bug is located into the uforge product.

Regards,
Joris
