### ISSUE TITLE
A scan name including a space cannot be specified with hammr scan run.

### ISSUE THREAD

**Issue by Yorche** [usharesoft/hammr#140]
- Phenomenon
  If a scan name including a space is specified, it becomes an argument error.
- Environments
  AppCenter3.6-4
  hammr-3.6==1.0
  uforge-python-sdk==3.6.0.9

Hammr

```
[root@Hammr36 ~]# hammr scan run --ip 10.124.111.120 --scan-login root --name "test scan"
INFO: no username nor password provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.json
INFO: Using url http://10.124.111.124/api
ERROR: ERROR: In Arguments: unrecognized arguments: scan
```

**Comment by Yorche** [comment]
[OTRS https://support.usharesoft.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=1191 ]

**Comment by AliceAlbano** [comment]
With the current library used for parsing arguments (argparse), it is not possible to use spaces in an argument expect like this : '"name with space"' or this : "name\ with \ space". The PR #406 updated the doc to explain this workaround, if we want to have the support for something like this, we should consider changing our parser. In this case we should reopen a new issue for changing our parser.
