### ISSUE TITLE
A scan name including a space cannot be specified with hammr scan import.

### ISSUE THREAD

**Issue by Yorche** [usharesoft/hammr#141]
- Phenomenon
  If the name including a space is specified, it becomes an argument error.
- Environments
  AppCenter3.6-4
  hammr-3.6==1.0
  uforge-python-sdk==3.6.0.9

```
[root@Hammr36 ~]# hammr scan import --id 17 --name "test import" --version 1
INFO: no username nor password provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.json
INFO: Using url http://10.124.111.124/api
ERROR: ERROR: In Arguments: unrecognized arguments: import
```

[OTRS https://support.usharesoft.com/otrs/index.pl?Action=AgentTicketZoom;TicketID=1193 ]

**Comment by jgweir** [comment]
Fixed in PR #215 , closing.
