### ISSUE TITLE
partial duplicates in hammr documentation for authentication

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#142]
I was looking for the parameter to accept self-signed certificates in the hammr credential files.
On page
http://docs.usharesoft.com/projects/hammr/en/latest/pages/authentication/overview.html#using-a-credential-file
(section Authentication in the documentation), this is not mentioned.
Then I discovered that there is the following page in Getting Started
http://docs.usharesoft.com/projects/hammr/en/latest/pages/getting-started/launch-hammr.html#using-a-credential-file
which mentions the acceptAutoSigned parameter.

The goal of this issue is to make the documentation coherent, possibly by removing the information about credential files in Getting Started -> Lauching hammr, and replace it with the pointer to the Authentication page.

**Comment by emuus** [comment]
this was covered in https://github.com/usharesoft/hammr/pull/144
