### ISSUE TITLE
CMDs are completely broken - only help is displayed

### ISSUE THREAD

**Issue by darkyat** [usharesoft/hammr#17]
Unfortunately the command handling seems to be completely broken. I've installed it via pip and from a trunk checkout and whatever command I use the help will be display.

e.g
$ hammr os list
usage: hammr [-a URL] [-u USER] [-p PASSWORD] [-v] [-h] [cmds [cmds ...]]

commands:
  Available hammr commands

Verified at Ubuntu 12.04 and Debian Wheezy.

$ hammr -v
hammr version '0.2.3'

**Comment by obourdon** [comment]
This is also fixed by the integration of issue #38
