### ISSUE TITLE
RFE: add information on how to use supervision in hammr authentication

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#171]
For authenticating in hammr using supervision mode (i.e. if the user with login userA has the entitlement to supervise, and wants to supervise userB), the doc does not mention the syntax to use.

The way to do it is to use for the user name
"userA\userB"

This information should appear in the following doc pages:
http://docs.usharesoft.com/projects/hammr/en/latest/pages/authentication/overview.html
and/or
http://docs.usharesoft.com/projects/hammr/en/latest/pages/getting-started/launch-hammr.html

**Comment by emuus** [comment]
Done in PR https://github.com/usharesoft/hammr/pull/312

**Comment by AliceAlbano** [comment]
The PR has been merged, this issue should be fixed so I close it.
