### ISSUE TITLE
Documentation on image publication is misleading regarding cloud accounts

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#173]
In the documentation page
http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/machine-image-publish.html
the reader can have the impression that the cloud account may not have yet been created.
In fact, the cloud account must be created beforehand using "hammr account create".
This should be clearly stated.

**Comment by emuus** [comment]
this is already there, with a link to creating cloud account
