### ISSUE TITLE
Add information in the documentation about changing the installed hammr version

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#177]
The current documentation only mentions how to upgrade hammr.
http://docs.usharesoft.com/projects/hammr/en/latest/pages/getting-started/installation.html (see respective OS pages).
However, only one version of hammr can be installed at a time, and since a given hammr version only work with a given AppCenter version.
Thus, when working with several AppCenter versions, it may be necessary to go back and forth between several versions of hammr.
The documentation should mention that not only hammr should be pip removed, but also the Python SDK.

**Comment by emuus** [comment]
This has been added to this PR : https://github.com/usharesoft/hammr/pull/266/commits/90ae552e4ca815fa0c873b55d23535fc30d0e3d0
