### ISSUE TITLE
AWS account need to be updated

### ISSUE THREAD

**Issue by jbremond** [usharesoft/hammr#178]
Some Information inside AWS account are not needed anymore. For example:

x509Cert
x509PrivateKey

This need to be cleanup

**Comment by bastienmartin** [comment]
Possible duplicate https://github.com/usharesoft/hammr/issues/409

**Comment by AliceAlbano** [comment]
This one will be fixed by the issue #430

**Comment by AliceAlbano** [comment]
Fixed by PR #432
