### ISSUE TITLE
hammr image delete command fails when try to delete the image which is generated from scan

### ISSUE THREAD

**Issue by Yorche** [usharesoft/hammr#179]
*Environment*
   hammr 3.6.1.1
   UForge V3.6-7
 

*Steps to reproduce*
 - How to reproduce
   1.generate the image using hammr scan build command
   2.delete the image which is result of 1 using hammr image delete command

<pre>

# hammr scan list --url https://192.168.2.117/api -u root -p XXXX
Getting scans for [root] ...
+----+---------------------------------+--------+-----------------+
| Id |              Name               | Status |  Distribution   |
+====+=================================+========+=================+
| 19 | hammr_25                        |        | CentOS 6 x86_64 |
+----+---------------------------------+--------+-----------------+
| 32 |         hammr_25 Scan #1        | Done   |                 |
+----+---------------------------------+--------+-----------------+

# cat create.json
{
  "builders": [
    {
      "type": "OVF or OVA",
      "hardwareSettings": {
        "memory": 1024
      },
      "installation": {
        "diskSize": "12288"
      }
    }
  ]
}

# hammr scan build --id 32 --file create.json --url https://192.168.2.117/api -u root -p XXXX
|>>>>>>>>>>>>>>>>>>>>>>>>| 100%: Done, created on ... |<<<<<<<<<<<<<<<<<<<<<<<|
Validating the template file [create.json] ...
OK: Syntax of template file [create.json] is ok
Generating 'OVF or OVA' image (1/1)
OK: Generation 'OVF or OVA' ok

# hammr image list --url https://192.168.2.117/api -u root -p XXXX
Getting all images and publications for [root] ...
Images:
+----+------------+---------+------+-----------------+---------------------+------+------------+-------------------+
| Id |    Name    | Version | Rev. |     Format      |       Created       | Size | Compressed | Generation Status |
+====+============+=========+======+=================+=====================+======+============+===================+
| 30 | hammr_25   | Scan #1 | 1    | OVF or OVA      | 2017-01-31 20:23:46 | 0B   | X          | Done              |
+----+------------+---------+------+-----------------+---------------------+------+------------+-------------------+

# hammr image delete --id 30 --url https://192.168.2.117/api -u root -p XXXX
Searching image with id [30] ...
+----+----------+---------+------+------------+---------------------+------+------------+--------+
| Id |   Name   | Version | Rev. |   Format   |       Created       | Size | Compressed | Status |
+====+==========+=========+======+============+=====================+======+============+========+
| 30 | hammr_25 | Scan #1 | 1    | OVF or OVA | 2017-01-31 20:23:46 | 0B   | X          | Done   |
+----+----------+---------+------+------------+---------------------+------+------------+--------+

Do you really want to delete image with id 30 [Y/n]
ERROR: UForge Error '404' with method: DELETE http://192.168.2.117:8080/ufws/users/root/appliances/32/images/30
Message:
        Appliance with id [32] not found.
==================
</pre>

*Root cause(s)*
The next error messages  are displayed in the logs: 
2017-02-02 09:31:43,537 uforge-web-service  INFO (UDispatcher.java:UDispatcher:205)(10.0.0.222)(root)(DELETE)(http://10.1.2.150:8080/ufws/users/root/appliances/1/images/2) - *machineImage_delete* - PP_uid=root,PP_aid=1,PP_itid=2
2017-02-02 09:31:43,540 uforge-web-service  WARN (URIService.java:URIService:187)(10.0.0.222)(root)(DELETE)(http://10.1.2.150:8080/ufws/users/root/appliances/1/images/2) - Appliance with id [1] not found in database
2017-02-02 09:31:44,875 uforge-web-service CLIENT (AbstractErrorFilter.java:AbstractErrorFilter:58)(10.0.0.222)(root)(DELETE)(http://10.1.2.150:8080/ufws/users/root/appliances/1/images/2) - Appliance with id [1] not found.

but when image is deleted from UI the messages in log is: 
2017-02-02 09:35:18,200 uforge-web-service  INFO (UDispatcher.java:UDispatcher:205)(10.1.2.150)(root)(DELETE)(http://10.1.2.150:8080/ufws/users/root/scannedinstances/1/scans/1/images/2) - *scanImageGeneration_delete -* PP_uid=root,PP_siid=1,PP_sid=1,PP_sitid=2

**Comment by AliceAlbano** [comment]
This has been fixed by PR #318
