### ISSUE TITLE
wrong version mentioned in installation instructions for hammr 3.7-2

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#185]
On page https://github.com/usharesoft/hammr/tree/hammr-uforge-3.7-2
the installation instructions are pip install --upgrade hammr-3.6
Should be pip install --upgrade hammr==3.7-2

according to http://usharesoft-docs.readthedocs.io/projects/hammr/en/latest/pages/getting-started/install-compatibility.html#install-compatibility

**Comment by bastienmartin** [comment]
It seems that be corrected. I do not find this typo anymore.

**Comment by Numerinico** [comment]
thx @bastienmartin closing this.
