### ISSUE TITLE
Builder example file for vbox (vbox-builder.json) gives a wrong information

### ISSUE THREAD

**Issue by AliceAlbano** [usharesoft/hammr#198]
The type of the builder must be "VirtualBox", as specified in the [documentation](http://docs.usharesoft.com/projects/hammr/en/latest/pages/templates-spec/builders/builders-vbox.html). In the exemple file in the source box, type used is "vbox", and the generation fails.

**Comment by bastienmartin** [comment]
Regarding this doc http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-vbox.html
The type is ok and the example is working, tested with hammr 3.8.4 and AppCenter 3.8.FP4

**Comment by Numerinico** [comment]
Thx @bastienmartin , closing this.
