### ISSUE TITLE
Version check does not occur when using commands, but occurs when using only "hammr"

### ISSUE THREAD

**Issue by AliceAlbano** [usharesoft/hammr#199]
When lauching 
`hammr -u user -p passwd --url myurl`
I obtain this error:
`ERROR: Sorry but this version of Hammr (version = '3.7.3') is not compatible with the version of UForge (version = '3.7.fp3-SNAPSHOT').`
`ERROR: Please refer to 'Install Compatibility' section in the documentation to learn how to install a compatible version of Hammr.`

But when I launch 
`hammr template build --file nginx-template.json -u user -p passwd --url myurl`
I do not have any errors

**Comment by Maxime93** [comment]
Taking care of it.

**Comment by jgweir** [comment]
Fixed with PR #219 , closing
