### ISSUE TITLE
Using a relative path to the json file seems to invoke an error

### ISSUE THREAD

**Issue by jgweir** [usharesoft/hammr#20]
Using the following example, invokes an error in hammr:

```
hammr template create --file ./base-template.json
error downloading ./base-template.json: local file url may start with / or file:. Unknown url of type: ./base-template.json
```

**Comment by obourdon** [comment]
This seems to be fixed

**Comment by jbremond** [comment]
I have reproduced the issue with hammr 0.2.5.8

**Comment by jbremond** [comment]
For the master, this code is now in another project: https://github.com/usharesoft/ussclicore

The fix as been back-port there.

I close the issue
