### ISSUE TITLE
"install native package"option is reset after importing my softwares with templates.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#23]
"Install this native package as part of the generation ?" option is reset to ON after importing my softwares with templates.
Hereunder is how to reproduce this issue.

- Create a template which has a mysoftware a packages of which is rpm and install during generation option is OFF.
- Export the template with Hammr.
- Remove or rename original template and mysoftware and import the template.
- The install option of the imported software is reset to ON.

**Comment by usharesoft** [comment]
THis is not a bug in hammr product. I closed the ticket
