### ISSUE TITLE
Integration tests fail

### ISSUE THREAD

**Issue by cinlloc** [usharesoft/hammr#248]
There are a lot of error when running integration tests. 

```
cd hammr/tests/integration
export TEST_USER=myuser
export TEST_PASSWORD=mypassword
export TEST_URL=http://myforge:8080/ufws
python test.py
```

`>>>`

```
...
----------------------------------------------------------------------
Ran 30 tests in 195.054s

FAILED (failures=5, errors=3)

```
Note: integration tests are not run by CI, they have to be manually run for now.

**Comment by cinlloc** [comment]
Integration tests output: [integration-results.txt](https://github.com/usharesoft/hammr/files/1183325/integration-results.txt)

**Comment by AliceAlbano** [comment]
Integration tests were successful in 3.8.fp5 branch, please reopen issue if another problem in IT tests happens
