### ISSUE TITLE
cannot publish or download images generated with Hammr.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#25]
Hi,

I cannot publish or download images generated with Hammr.
UForge returns a message:
> Unable to publish this image as this image is only a simulation (no actual image created).

json file is:
```
{
  "stack" : {
    "name" : "test",
    "version" : "1.0",
    "description": "This is a hammr example.",
    "os" : {
      "name" : "RedHat Enterprise Linux",
      "version" : "6",
      "arch" : "i386",
      "profile" : "Minimal",
      "pkgs": [
        {
          "name": "php"
        },
        {
          "name": "php-cli"
        },
        {
          "name": "php-common"
        },
        {
          "name": "php-mysql"
        }
      ]
    },
    "installation" : {
      "keyboard": "jp106",
      "timezone": "Asia/Tokyo",
      "diskSize": 20480,
      "swapSize": 512
    }
  },
  "builders": [
    {
      "type": "openstack-qcow2",
      "diskSize": 20480
    }
  ]
}
```

Hammr command is:
```
$ hammr template create --file test1.json
$ hammr template build --file test1.json
```

What is the simulation?

Thanks.

**Comment by MaxTakahashi** [comment]
Hammr version is 0.2.4.3, UForge is 3.5.0.

Thanks.

**Comment by usharesoft** [comment]
Will be integrated into the next hammr release. This bug affect only hammr 0.2.4.x versions.
Simulation is a mode in uforge to do only the checkings dependencies steps (use for QA for exemple). The option is available with the --simulate arg to template build command

**Comment by MaxTakahashi** [comment]
Thank you for the fix and explanation.

Best Regards.
