### ISSUE TITLE
hammr documentation needs to improve the list of Linux pre-requisite packages

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#265]
Following my struggle to install hammr on my Fedora 25 laptop I'm logging this RFE.

[Symptom]
When installing hammr as described in the documentation http://docs.usharesoft.com/projects/hammr/en/latest/pages/getting-started/installation.html (with all prerequisite packages correctly installed), the last command
`pip install hammr`
returns the following error:
```
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-beoKWj/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory
error: command 'gcc' failed with exit status 1
```

[How to solve the issue]
It appears that one file is missing, /usr/lib/rpm/redhat/redhat-hardened-cc1.

The following link https://stackoverflow.com/a/34641068/4126482 indicates that
`sudo dnf install redhat-rpm-config`
solves the problem, which it did for me (after the installation of this redhat-rpm-config package, pip install hammr worked fine).

The objective of this RFE is to improve the hammr documentation and add some text on page http://docs.usharesoft.com/projects/hammr/en/latest/pages/getting-started/install-linux.html along the line of:

It may happen that the pip install hammr command will fail with an error message containing
`    gcc: error: /usr/lib/rpm/redhat/redhat-hardened-cc1: No such file or directory`
In this case, run yum install redhat-rpm-config and launch pip install hammr again.

**Comment by alefebvr** [comment]
Second area where I found an error.
When installing hammr on Ubuntu 16.04, I encountered an error running the pip install hammr command:
```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -lxslt -lexslt -lxml2 -lz -lm -o build/lib.linux-x86_64-2.7/lxml/etree.so
    /usr/bin/ld: cannot find -lz
```
As described in https://stackoverflow.com/questions/3373995/usr-bin-ld-cannot-find-lz, 
```
sudo apt-get install libz-dev
```
solves the issue for Ubuntu. I've tested this and the installation of hammr works.
We should add this pre-requisite (libz-dev) to the Ubuntu list of prerequisites.

**Comment by emuus** [comment]
Both these suggestions are covered in PR https://github.com/usharesoft/hammr/pull/266

**Comment by emuus** [comment]
Covered in PR https://github.com/usharesoft/hammr/pull/274
