### ISSUE TITLE
documentation install compatibility page does not list the hammr versions for 3.7-5, 6, 7

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#269]
Page http://docs.usharesoft.com/projects/hammr/en/latest/pages/getting-started/install-compatibility.html it not up to date and should add entries for UForge versions 3.7-5, 3.7-6 and 3.7-7.

**Comment by emuus** [comment]
Covered in PR https://github.com/usharesoft/hammr/pull/272
