### ISSUE TITLE
Hammr for Python 3

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#28]
Hammr for Python 3 is possible ?

Thanks

**Comment by usharesoft** [comment]
Hello,

Technically, it would be possible to make Hammr work with Python 3, but:
- it would require additional development
- Hammr would then not be compatible with Python 2 (unless we maintain 2 versions of Hammr, one for Python 2 and one for Python 3).

Hope this helps,

Best,

Alex for UShareSoft
