### ISSUE TITLE
K5 Builder Doc section has madatory hardware parameters - this is not an option

### ISSUE THREAD

**Issue by jgweir** [usharesoft/hammr#297]
The following should be removed from the K5 builder docs:

hardwareSettings (mandatory): an object providing hardware settings to be used for the machine image. The following valid keys for hardware settings are: * memory (mandatory): an integer providing the amount of RAM to provide to an instance provisioned from the machine image (in MB). * hwType (optional): an integer providing the hardware type for the machine image. This is the VMware hardware type: 4 (ESXi>3.x), 7 (ESXi>4.x) or 9 (ESXi>5.x)

Also there are certain indenting issues in the installation bullet

**Comment by emuus** [comment]
Fixed in PR https://github.com/usharesoft/hammr/pull/299
