### ISSUE TITLE
Docs: Authentication section, should update the URL with correct examples

### ISSUE THREAD

**Issue by jgweir** [usharesoft/hammr#298]
We should use the uforge online URL as the examples:
http://docs.usharesoft.com/projects/hammr/en/latest/pages/authentication/overview.html#

Need to check the rest of the docs for any URL mentions

"url" : "https://uforge.usharesoft.com/api"

**Comment by emuus** [comment]
Found on these 3 pages 
- http://usharesoft-docs.readthedocs.io/projects/hammr/en/latest/pages/authentication/overview.html?highlight=uforge.usharesoft.com%2Fapi
- http://usharesoft-docs.readthedocs.io/projects/hammr/en/latest/pages/getting-started/install-compatibility.html?highlight=uforge.usharesoft.com%2Fapi
- http://usharesoft-docs.readthedocs.io/projects/hammr/en/latest/pages/getting-started/launch-hammr.html?highlight=uforge.usharesoft.com%2Fapi

**Comment by emuus** [comment]
However, the sample URL should be one for uforge/api. Giving the docs URL in these examples seems a bit misleading (we want the user to realize that they need to enter their uforge address). Can we use something like this instead?: "https://<your-uforge>/api"

**Comment by jgweir** [comment]
Yes,

**Comment by emuus** [comment]
Fixed in PR https://github.com/usharesoft/hammr/pull/311
