### ISSUE TITLE
Publish to some target platform does not work (builders are obsolete)

### ISSUE THREAD

**Issue by AliceAlbano** [usharesoft/hammr#359]
When trying publish images to these target platforms, the publish fails:
- VCD, susecloud, abiquo, nimbula, eucalyptus, gce (google compute engine?)

The builders used for these target platform are obsolete (they do not work for months or years), we need to know which one we support currently.

**Comment by Numerinico** [comment]
Please also check and fix on stable 3.8

**Comment by AliceAlbano** [comment]
Fixed by PR #384
