### ISSUE TITLE
Compiling from src fails on mac osx

### ISSUE THREAD

**Issue by bala-v** [usharesoft/hammr#37]
Following documentation:-

http://hammr.io/?page_id=695
1: curl -O https://pypi.python.org/pypi/uforge_python_sdk
2: cd uforge_python_sdk
3: python setup.py build;sudo setup.py. install
4: git clone https://github.com/usharesoft/hammr.git
5: cd hammr
6: python setup.py build
osx-mac:src$ python setup.py build
running build
running build_py
running build_scripts
7: sudo setup.py install
osx-mac:src$ sudo setup.py install
sudo: setup.py: command not found

any ideas?.

**Comment by jbremond** [comment]
Hello,

The problem is located in your last command: 
```
sudo setup.py install
```
The command is:
```
sudo python setup.py install
```

Regards,
joris
