### ISSUE TITLE
documentation: x509 parameters in the Amazon AWS builder section should be removed

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#409]
The hammr documentation page about Amazon AWS builders http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-aws.html mentions x509Cert and x509PrivateKey as mandatory arguments.
However, those are not used by UForge AppCenter any more and should be removed.

**Comment by bastienmartin** [comment]
Possible duplicate https://github.com/usharesoft/hammr/issues/178

**Comment by AliceAlbano** [comment]
Fixed by PR #432
