### ISSUE TITLE
builder for Suse Cloud fails

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#410]
When trying to build a template with the builder from the documentation, the following error is displayed:
```
hammr> template build --file templatesuse.yml
INFO: You provided a yaml file, checking...
Generating 'Suse Cloud' image (1/1)
ERROR: Builder type unknown: Suse Cloud
```
I used the example provided in the documentation for the builder, http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-suse-cloud.html

**Comment by AliceAlbano** [comment]
Fixed by #429
