### ISSUE TITLE
builder for VMWare VCloud Director fails

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#412]
When trying to build a template with the builder from the documentation http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-vcd.html, the following error is displayed:
```
hammr> template build --file templatevcd.yml
INFO: You provided a yaml file, checking...
Generating 'VMware vCloud Director' image (1/1)
ERROR: Builder type unknown: VMware vCloud Director
```

**Comment by AliceAlbano** [comment]
Fixed by #429
