### ISSUE TITLE
Builder for Outscale

### ISSUE THREAD

**Issue by bastienmartin** [usharesoft/hammr#415]
When trying to build a template with the builder from the documentation http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-outscale.html, the following error is displayed:

```
INFO: Checking default credentials file...
INFO: no username provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.yml
you provided a yaml file, checking the syntax...
INFO: You provided a yaml file, checking...
Generating 'Outscale' image (1/1)
ERROR: Builder type unknown: Outscale
```

**The YAML file**
```
---
stack:
  name: PSTAS-69
  version: '1.0'
  installation:
    internetSettings: basic
    diskSize: 12288
    swapSize: 512
  os:
    name: CentOS
    version: '7'
    arch: x86_64
    profile: Minimal
builders:
- type: Outscale
  account:
    type: Outscale
    name: My Outscale Account
    accessKey: 789456123ajdiewjd
    secretAccessKey: ks30hPeH1xWqilJ04
  installation:
    diskSize: 10240
  region: eu-west-2
  description: centos-template
```

**Comment by AliceAlbano** [comment]
Are you sure outscale target format was enabled on your forge? I had the same error as you when I tried and oustscale was not enabled. After enabling it, it works fine with your builder

**Comment by AliceAlbano** [comment]
Are you sure outscale target format was enabled on your forge? I had the same error as you when I tried and oustscale was not enabled. After enabling it, it works fine with your builder

**Comment by bastienmartin** [comment]
You are right, I tried with an enabled outscale target and it works
You can close this issue, it was a mistake from my side.

**Comment by AliceAlbano** [comment]
Thank you for your comment, an issue is already logged to improve this error message (#431 )
