### ISSUE TITLE
How to set up the dev environment to contribute

### ISSUE THREAD

**Issue by bastienmartin** [usharesoft/hammr#469]
Hello,

As an external dev, I would like a **complete** guide to set up my pycharm environment to contribute to this project:
- Which packages I have to install on my OS.
- Which python packages I have to install on my python environment.
- etc.

The aim is to have a functional PyCharm env from a fresh install of a RedHat-based distro like CentOS or Fedora.

Thank you.

**Comment by AliceAlbano** [comment]
You have a Hammr wiki here with a section contribute : https://github.com/usharesoft/hammr/wiki
It can be a start, and it can also be completed if needed !

**Comment by bastienmartin** [comment]
From a fresh installed OS, launch pycharm and open the hammr projet or git clone with pycharm.
Wait a moment (indexing, skeletons, ) and open any file.

Packages requirements:
```
- uforge_python_sdk>=3.8.8
- httplib2==0.9
- textable==0.8.1
- progressbar==2.3
- argparse
- paramiko==1.12
- pyparsing==2.0.2
- pyyaml==3.12
- hurry.filesize==0.9
- termcolor==1.1.0
- junit-xml==1.3
- xmlrunner==1.7.7
- ussclicore==1.0.11
- mock
```

**Comment by bastienmartin** [comment]
To install python dependencies:
```
[root@localhost ~]# curl https://bootstrap.pypa.io/get-pip.py -O
[root@localhost ~]# python get-pip.py
[root@localhost ~]# pip install progressbar==2.3
[root@localhost ~]# pip install httplib2==0.9
[root@localhost ~]# pip install mock
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install 
[root@localhost ~]# pip install

**Comment by bastienmartin** [comment]
Ok it seems it's working if you follow this steps:
1. yum install -y git gcc python-devel libxml2-devel libxslt-devel
1. curl https://bootstrap.pypa.io/get-pip.py -O
1. python get-pip.py pip==8.1.1
1. Launch pycharm
1. Open the project hammr
1. Wait a moment (Updating Python Interpreter and Updating Indices) and open any python file from the project.
1. When you have the message "Package requirements...", click on "Install requirements"
1. Enjoy!

**Comment by bastienmartin** [comment]
I will PR something

**Comment by bastienmartin** [comment]
Hello, on the wiki (https://github.com/usharesoft/hammr/wiki/Contribute), below this text:
```
If you want to contribute to Hammr, you can review code for opened pull requests, fix logged issues or propose new features in a dedicated pull request. If you encounter issues or bugs using Hammr, you can log them.

You can also open issues if you have an idea for improvement, or help improving the code coverage, by writing unit tests or integration tests.
```

Can you add something like this:

```
On a RedHat-based distro (Fedora, CentOS, etc.), you will need to install these packages:
* gcc
* python-devel
* libxml2-devel
* libxslt-devel

And PyCharm will need pip==8.1.1 to install the required python packages.
```

It's enough to have a working environment.
Thank you !

**Comment by locobastos** [comment]
The next step is to explain how to PR.

**Comment by bastienmartin** [comment]
Regarding the dependencies, I added them directly in the Wiki.
Regarding the pull request, it a GitHub mechanism, I had to learn how it works.
