### ISSUE TITLE
Hammr should support YAML as input

### ISSUE THREAD

**Issue by jbremond** [usharesoft/hammr#57]

**Comment by hugo6** [comment]
Currently working on

**Comment by hugo6** [comment]
That depends on :
Uforge https://projects.usharesoft.com/issues/5388
Ussclicore https://github.com/usharesoft/ussclicore/issues/15

**Comment by hugo6** [comment]
I didn't do the documentation for YAML REF export in uforge and Hammr

**Comment by thachmai** [comment]
Can this issue be closed now?
