### ISSUE TITLE
Why "easy_install progressbar==2.3" is needed before "pip install hammr" ?

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#65]
Hi,

Maybe this is a general question.

In the installation guide (http://hammr.io/?page_id=695), progressbar=2.3 is installed with easy_install before installing hammr with pip.

```
$ easy_install progressbar==2.3
$ pip install hammr
```

Why is it needed ?

progressbar is also required in setup.py.

```
requires=['uforge_python_sdk>=3.6',
                    'httplib2==0.9',
                    'texttable>=0.8.1',
                    'progressbar==2.3',
                    'argparse',
                    'paramiko==1.12',
                    'pyparsing==2.0.2',
                    'hurry.filesize==0.9',
                    'termcolor==1.1.0',
                    'junit-xml==1.3',
                    'xmlrunner==1.7.7',
                    'ussclicore']
```

It looks like the installation is succeeded without launching "easy_install progressbar==2.3".

Thanks.

**Comment by bastienmartin** [comment]
**Tested with Hammr 3.8.4 :**
This command is NOT needed.

**My test :**
`[bastien@bastien Docker]$ docker run --rm -i -t -v /data/Downloads:/home/developer centos bash`
`[root@3082fcc01080 ~]# yum install -y wget`
`[root@3082fcc01080 ~]# wget https://bootstrap.pypa.io/get-pip.py`
`[root@3082fcc01080 ~]# python get-pip.py`
`[root@3082fcc01080 ~]# yum install -y gcc python-devel libxml2-devel libxslt-devel which redhat-rpm-config`
`[root@3082fcc01080 ~]# pip install hammr`

**On the STDOUT :**
`Collecting hammr`
`Downloading https://files.pythonhosted.org/packages/07/38/20f9f3ab9e03fc527eb01ffb0888e27f2be2d50032be2264fbf99bb1ca27/hammr-3.8.4-py2-none-any.whl (108kB)`
`100% |################################| 112kB 2.6MB/s`
:snip:
`Collecting progressbar==2.3 (from hammr)`
`Downloading https://files.pythonhosted.org/packages/0f/e1/f30b72ecabba259c7c38dd0eb944a173effced3fd7de2c9c2902bd6f649a/progressbar-2.3.tar.gz`
:snip:
`Running setup.py bdist_wheel for progressbar ... done`
:snip:
`Successfully built texttable hurry.filesize termcolor paramiko junit-xml xmlrunner httplib2 pyyaml progressbar pyparsing cmd2 pycrypto lxml pyxb`
`Installing collected packages: texttable, argparse, hurry.filesize, termcolor, pyparsing, cmd2, pyyaml, progressbar, ussclicore, pycrypto, ecdsa, paramiko, junit-xml, requests, lxml, pyxb, uforge-python-sdk, xmlrunner, httplib2, hammr`
`Successfully installed argparse-1.4.0 cmd2-0.6.7 ecdsa-0.13 hammr-3.8.4 httplib2-0.9 hurry.filesize-0.9 junit-xml-1.3 lxml-3.3.5 paramiko-1.12.0 **progressbar-2.3** pycrypto-2.6.1 pyparsing-2.0.2 pyxb-1.2.4 pyyaml-3.12 requests-2.13.0 termcolor-1.1.0 texttable-0.8.1 uforge-python-sdk-3.8.4 ussclicore-1.0.11 xmlrunner-1.7.7`

**Comment by Numerinico** [comment]
Thanks @bastienmartin , we are closing this then.
