### ISSUE TITLE
Cannot export templates with My Software.

### ISSUE THREAD

**Issue by MaxTakahashi** [usharesoft/hammr#76]
Hi,

I cannot export templates with My Software components.

I attached WordPress archive to a CentOS 7 template and tried to export using Hammr.
https://wordpress.org/download/

The export looks like fine, but the archive size is just 8192 bytes.
```
[root@localhost tmp]# hammr template export --id 22
INFO: no username nor password provided on command line, trying credentials file
INFO: Using credentials file: /root/.hammr/credentials.json
INFO: Using url https://192.168.56.105/api
Exporting template with id [22] :
100%|###################################################################|
Downloading archive...
OK: Download complete of file [archive.tar.gz]
[root@localhost tmp]# ll archive.tar.gz
-rw-r--r-- 1 root root 8192 May 24 03:47 archive.tar.gz
```

Untar is failed with "Unexpected EOF in archive" error.
```
[root@localhost tmp]# tar -xvzf archive.tar.gz

gzip: stdin: unexpected end of file
bundles/
bundles/wp/
bundles/wp/4.5.2/
bundles/wp/4.5.2/wordpress-4.5.2.zip
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

The archive is created successfully on the UForge. I can untar the archive.
It looks like something has been happened while the download.
```
-bash-4.1# ll /tmp/USER_DATA/FactoryContainer/users/root/appliances/22/exports/17/WordPress.tar.gz
-rw-r--r-- 1 root root 8183409 May 23 18:41 /tmp/USER_DATA/FactoryContainer/users/root/appliances/22/exports/17/WordPress.tar.gz
-bash-4.1# tar -xvzf /tmp/USER_DATA/FactoryContainer/users/root/appliances/22/exports/17/WordPress.tar.gz -C /tmp/
bundles/
bundles/wp/
bundles/wp/4.5.2/
bundles/wp/4.5.2/wordpress-4.5.2.zip
config/
template.json
```

- hammr version '0.2.5.10'
- UForge 3.5.1-29.

Thanks.

**Comment by jbremond** [comment]
Thanks for this issue, we will to reproduce it in our environment.
It could be linked to this #69 evolution

**Comment by jbremond** [comment]
I have reproduced the issue and I will work on it as it it critical.

Regards,
Joris

**Comment by jbremond** [comment]
I have found the issue. It was a regression of an evolution inside the uforge-python-sdk and I have fixed it.
You need to do the following command if hammr is already installed:
`sudo pip install uforge-python-sdk==3.5.1.5 --upgrade`

Regards,
Joris

**Comment by MaxTakahashi** [comment]
Thanks for the quick update, Joris-San.
I have confirmed the fix.

Best Regards,
Takahashi.
